name: Unit Tests macOS

on: [ push ]

jobs:
  build:
    name: ${{ matrix.compiler_name }}
    runs-on: macos-latest

    strategy:
      matrix:
        compiler_name: [build_gcc11, build_clang]
        include:
          - compiler_name: build_gcc11
            c_compiler: gcc-11
            cxx_compiler: g++-11

          - compiler_name: build_clang
            c_compiler: clang
            cxx_compiler: clang++

    steps:
      - uses: actions/checkout@v2

      - name: xcode-select
        run: sudo xcode-select -s "/Applications/Xcode_14.1.app"

      - name: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNIT_TESTS=TRUE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -S ./source

      - name: build
        run: cmake --build ./

      - name: unit-tests
        run: ./unittests

      - name: cmake-utils
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNIT_TESTS=TRUE -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -S ./utils -B ./utils

      - name: build-utils
        run: cmake --build ./utils

      - name: unit-tests-utils
        run: ./utils/differtests
        