name: Unit Tests Ubuntu

on: [ push ]

jobs:
  build:
    name: ${{ matrix.compiler_name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler_name: [build_gcc7, build_gcc8, build_gcc9, build_gcc10, build_clang8, build_clang9, build_clang10]
        include:
          - compiler_name: build_gcc7
            c_compiler: gcc-7
            cxx_compiler: g++-7

          - compiler_name: build_gcc8
            c_compiler: gcc-8
            cxx_compiler: g++-8

          - compiler_name: build_gcc9
            c_compiler: gcc-9
            cxx_compiler: g++-9

          - compiler_name: build_gcc10
            c_compiler: gcc-10
            cxx_compiler: g++-10

          - compiler_name: build_clang8
            c_compiler: clang-8
            cxx_compiler: clang++-8

          - compiler_name: build_clang9
            c_compiler: clang-9
            cxx_compiler: clang++-9

          - compiler_name: build_clang10
            c_compiler: clang-10
            cxx_compiler: clang++-10

    steps:
      - uses: actions/checkout@v2

      - name: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNIT_TESTS=TRUE  -G "CodeBlocks - Unix Makefiles" -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -S ./source

      - name: build
        run: cmake --build ./

      - name: unit-tests
        run: ./unittests
