name: Build Ubuntu

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" -DCMAKE_CXX_COMPILER=g++-7 -S ./source
      
    - name: build
      run: cmake --build ./
