name: Unit Tests Windows

on: [ push ]

jobs:
  build_mingw:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNIT_TESTS=TRUE -G "MinGW Makefiles" -S ./source
      
    - name: build
      run: cmake --build ./

    - name: unit-tests
      run: ./unittests

    - name: cmake-utils
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNIT_TESTS=TRUE -G "MinGW Makefiles" -S ./utils -B ./utils

    - name: build-utils
      run: cmake --build ./utils

    - name: unit-tests-utils
      run: ./utils/utiltests
      
  build_msvc:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: cmake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -G "Visual Studio 17 2022" -A x64 -DENABLE_UNIT_TESTS=TRUE -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -S ./source

      - name: build
        run: cmake --build ./ --config Debug

      - name: unit-tests
        run: ./Debug/unittests

      - name: cmake-utils
        working-directory: ./utils
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -G "Visual Studio 17 2022" -A x64 -DENABLE_UNIT_TESTS=TRUE -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -S ./

      - name: build-utils
        run: cmake --build ./utils --config Debug

      - name: unit-tests-utils
        run: ./utils/Debug/utiltests
